# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5566696f2f4c1253c3dd6425c6deb7e68557f4e43bb895a3427cb52a782797c44b9c4cf30c16b9ba7c2a70a368f5bec5fa3d74177a61238063d65ccdd3ae0f0a

test:
  secret_key_base: fdefc0a0d721bf990e3230a495050cf1d6ae2dac4ccf6033d871fb48931dbaf71ed88e5c00a127b15269f6a1f363e36f9c7c9d5f50344d73e1044ef37aa80a06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
